In [1]:
import numpy as np
import pickle
import h5py

In [2]:
h5f_valid = h5py.File('./Container/valid_cpl', 'r')
valid_features = h5f_valid['features_boolean'][:]
answer = h5f_valid['labels_id'][:].astype(np.int64)
answer_ = h5f_valid['labels_one_hot'][:]
h5f_valid.close()

In [3]:
valid_features

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [4]:
answer

array([2061, 6421, 2945, ..., 2442, 4355, 5377], dtype=int64)

In [5]:
answer[0]

2061

In [6]:
answer_

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [7]:
np.nonzero(answer_[0])

(array([2060], dtype=int64),)

In [8]:
np.nonzero(valid_features[0])

(array([  58,  232, 1307, 2337, 3331, 6682], dtype=int64),)

In [9]:
answer_[0, 2060]

1.0